"""Create table program level

Revision ID: 811556ca2f36
Revises: 
Create Date: 2024-03-18 12:45:55.603068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811556ca2f36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_level')
    # ### end Alembic commands ###
